title: Kristóf Huszár
logo: /assets/img/avatar.jpg
description: Postdoctoral researcher at Inria
theme: jekyll-theme-minimal
markdown: kramdown
url: "https://kristofhuszar.github.io"
plugins:
  - jekyll-sitemap
